stages:
  - update
  - merge_requests

variables:
  VAULT_ADDR: https://vault.sec.internal.scaleway.com

.base:
  image: docker-registry.infra.online.net/auth/protoc-gen:v2-latest
  tags: [ docker ]
  before_script:
    # Trust scaleway CA certificate
    - wget -q https://nexus-registry.infra.online.net/repository/raw-registry/security/ca.pem -O /usr/local/share/ca-certificates/scaleway_internal_root_ca.crt
    - update-ca-certificates
    - export GITLAB_TOKEN=$(vault kv get -field token developer-tools_kv/gitlab)
    # Add credential to allow git push
    - git remote set-url origin https://oauth2:$GITLAB_TOKEN@gitlab.infra.online.net/protobuf/scaleway-sdk-go.git
    # Set username and email
    - git config --global user.name 'devtools-ci-cd'
    - git config --global user.email 'devtools-ci-cd@scaleway.com'
    - git config --global advice.detachedHead false

# Will update the generated file and tag a git version when the protobuf/protobuf repository is tagged.
update:
  extends: .base
  stage: update
  only:
    variables:
      - $JOB == "update-protobuf"
  script:
    - git fetch origin
    - git branch -D master || true
    - git checkout --track origin/master
    - ./scripts/update-protobuf.sh --tag $TAG --gitlab-token $GITLAB_TOKEN

# Will create a branch and open a pull request containing the changes generated by a code change in protobuf/protobuf
merge-request:
  extends: .base
  stage: merge_requests
  only:
    variables:
      - $JOB == "merge-request-protobuf"
  script:
    - git fetch origin
    - git branch -D $UPSTREAM_BRANCH || true
    - git checkout -b $UPSTREAM_BRANCH
    - ./scripts/merge-request-protobuf.sh --branch $UPSTREAM_BRANCH --gitlab-token $GITLAB_TOKEN
